version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2016"
  module_system = "commonjs"
  environment = ["browser"]
  style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true
